project:
  type: website

website:
  title: "Dr. Anoop's PhD Journal"
  sidebar:
    contents:
      - index.qmd
      - text: "📖 Methodology"
        file: methodology_b.qmd
      - text: "📈 Simulation Results"
        file: simulation_results.qmd
      - audit.qmd

format:
  html:
    theme: cosmo
    toc: true
