"""
Description: Heatmap visualization for Method B Security Margin across Control Modes.
Project: PhD Thesis - Physics-Informed Protection for IBR-Dominated Microgrids
Author: Dr. Anoop Eluvathingal (Senior Scientist)
Logic Layer: Visualization Suite
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

def generate_security_heatmap(input_csv='analytics_validation/ici_audit_results.csv'):
    # Load the results generated by your ICI Audit Engine [cite: 2026-03-17]
    try:
        df = pd.read_csv(input_csv)
    except FileNotFoundError:
        print("ERROR: Run ici_audit_engine.py first to generate data.")
        return

    # Prepare data for Heatmap (Pivoting modes vs peak entropy)
    # Adding a dummy 'Sensitivity' axis to demonstrate the 2D safety zone
    sensitivity_levels = [0.10, 0.15, 0.20, 0.25] # Potential Relay Thresholds
    heatmap_data = []

    for threshold in sensitivity_levels:
        row = []
        for peak_noise in df['Peak_Entropy_Noise']:
            # Margin = Threshold - Noise (Positive is Secure)
            margin = threshold - peak_noise
            row.append(margin)
        heatmap_data.append(row)

    # Visualization
    plt.figure(figsize=(10, 6), dpi=300)
    sns.heatmap(heatmap_data, annot=True, cmap='RdYlGn', 
                xticklabels=df['Control_Mode'], 
                yticklabels=sensitivity_levels,
                cbar_kws={'label': 'Security Margin (Threshold - Noise)'})

    plt.title('Method B Security Margin: Control Loop Resilience Audit', fontsize=14, fontweight='bold')
    plt.xlabel('Inverter Control Mode', fontsize=12)
    plt.ylabel('Entropy Trip Threshold (σ)', fontsize=12)
    
    plt.tight_layout()
    plt.savefig('visualization/ici_security_heatmap.png')
    plt.show()
    print("SUCCESS: ici_security_heatmap.png generated. Province secured.")

if __name__ == "__main__":
    generate_security_heatmap()