function derive_partials()
%DERIVE_PARTIALS  Symbolic derivation of dH/dalpha and dH/dRx.
%
%   Builds the 4x4 cascaded-Gamma state-space symbolically in
%   (alpha, R_x), computes the single-frequency transfer function
%
%       H(j*omega; alpha, R_x) = C * (j*omega I - A)^{-1} B + D,
%
%   takes sym/diff with respect to alpha and R_x, simplifies, and
%   writes two callable MATLAB functions next to this file:
%
%       matlab/dH_dalpha.m     dH_dalpha(alpha, Rx, omega)  -> complex
%       matlab/dH_dRx.m        dH_dRx   (alpha, Rx, omega)  -> complex
%
%   The functions are generated via matlabFunction and shipped under
%   matlab/ alongside the rest of the project.  `test_partials.m`
%   confirms the analytic derivatives match a 1e-6 central finite-
%   difference at three (alpha, R_x) pairs to machine precision.
%
%   Convention is the cascaded-Gamma documented in
%   docs/AppendixA_derivation.tex.  Per-km parameters are the SI
%   defaults from faultloc_pi_section_model.m.

    here = fileparts(mfilename('fullpath'));

    % --- Symbols --------------------------------------------------------
    syms alpha Rx omega real
    syms R_per_km L_per_km C_per_km L_total R_load real positive

    L1 = alpha       * L_total;
    L2 = (1 - alpha) * L_total;

    R1 = R_per_km * L1;   X1 = L_per_km * L1;   C1 = C_per_km * L1;
    R2 = R_per_km * L2;   X2 = L_per_km * L2;   C2 = C_per_km * L2;

    A = [ -1/(Rx*C1)        0                  1/C1       -1/C1 ; ...
            0              -1/(R_load*C2)      0           1/C2 ; ...
           -1/X1            0                 -R1/X1       0    ; ...
            1/X2           -1/X2               0          -R2/X2 ];
    B = [0; 0; 1/X1; 0];
    Cv = [0  0  1  0];
    Dv = sym(0); %#ok<NASGU>

    % --- H(j*omega; alpha, Rx) -----------------------------------------
    I4 = eye(4);
    H  = simplify(Cv * ((1j*omega*I4 - A) \ B));

    % --- Partials -------------------------------------------------------
    dHa = simplify(diff(H, alpha));
    dHR = simplify(diff(H, Rx));

    fprintf('derive_partials: |H| symbolic OK\n');
    fprintf('derive_partials: |dH/dalpha| symbolic OK\n');
    fprintf('derive_partials: |dH/dRx|    symbolic OK\n');

    % --- Substitute SI defaults so the generated function takes only
    %     (alpha, Rx, omega) as inputs ------------------------------------
    defaults = struct( ...
        'R_per_km', 0.0728, ...
        'L_per_km', 0.927e-3, ...
        'C_per_km', 11.6e-9, ...
        'L_total',  100.0, ...
        'R_load',   1.0e6);

    dHa_si = subs(dHa, ...
        {R_per_km, L_per_km, C_per_km, L_total, R_load}, ...
        {defaults.R_per_km, defaults.L_per_km, defaults.C_per_km, ...
         defaults.L_total,  defaults.R_load});
    dHR_si = subs(dHR, ...
        {R_per_km, L_per_km, C_per_km, L_total, R_load}, ...
        {defaults.R_per_km, defaults.L_per_km, defaults.C_per_km, ...
         defaults.L_total,  defaults.R_load});

    matlabFunction(dHa_si, ...
        'File',  fullfile(here, 'dH_dalpha.m'), ...
        'Vars',  {alpha, Rx, omega}, ...
        'Optimize', true, ...
        'Comments', 'WP0.5 generated by derive_partials.m - do not edit by hand.');
    matlabFunction(dHR_si, ...
        'File',  fullfile(here, 'dH_dRx.m'), ...
        'Vars',  {alpha, Rx, omega}, ...
        'Optimize', true, ...
        'Comments', 'WP0.5 generated by derive_partials.m - do not edit by hand.');

    fprintf('wrote %s\n', fullfile(here, 'dH_dalpha.m'));
    fprintf('wrote %s\n', fullfile(here, 'dH_dRx.m'));
end
